from django.urls import path

from .views import (
    create_supplier,
    create_buyer,
    create_season,
    create_drop,
    create_product,
    create_order,
    create_delivery,
    product_view,
    edit_product,
    update_product,
    delete_product,
    shop_view,
    publish_prod,
    order_view,
    edit_order,
    update_order,
    dashboard,
    # inventory,

    SupplierListView,
    BuyerListView,
    SeasonListView,
    DropListView,
    # OrderListView,
    DeliveryListView,
)

urlpatterns = [
    path('dashboard/', dashboard, name='dashboard'),
    # path('inventory/', create_product, name='create-product'),
    path('create-supplier/', create_supplier, name='create-supplier'),
    path('create-buyer/', create_buyer, name='create-buyer'),
    path('create-season/', create_season, name='create-season'),
    path('create-drop/', create_drop, name='create-drop'),
    path('create-product/', create_product, name='create-product'),
    path('edit-product/<int:id>', edit_product, name = 'edit-product'),
    path('edit-order/<int:id>', edit_order, name = 'edit-order'),
    path('update-order/<int:id>', update_order, name = 'update-order'),
    path('update-product/<int:id>', update_product, name = 'ipdate-product'),
    path('delete-product/<int:id>', delete_product, name='delete-product'),
    path('publish-product/<int:id>', publish_prod, name='publish-product'), 
    path('create-order/', create_order, name='create-order'),
    path('create-delivery/', create_delivery, name='create-delivery'),

    path('supplier-list/', SupplierListView.as_view(), name='supplier-list'),
    path('buyer-list/', BuyerListView.as_view(), name='buyer-list'),
    path('season-list/', SeasonListView.as_view(), name='season-list'),
    path('drop-list/', DropListView.as_view(), name='drop-list'),
    path('product-list/', product_view, name='product-list'),
    path('shop-list/', shop_view, name='shop-list'),
    path('order-list/', order_view, name='order-list'),
    path('delivery-list/', DeliveryListView.as_view(), name='delivery-list'),
]